language: go
go_import_path: github.com/skydive-project/skydive

go:
    - 1.9.1

sudo: required
os:
    - linux
#    - linux-ppc64le
dist: xenial
services:
    - docker
addons:
    apt:
        packages:
            - openvswitch-switch
            - unzip
            - build-essential
            - flex
            - bison
            - libxml2-dev
            - libz-dev
            - liblzma-dev
            - libicu-dev
            - libc++-dev
            - bridge-utils
            - libdb5.3-dev
            - libgraph-easy-perl
            - screen
            - inotify-tools
            - realpath
            - libnuma-dev
            - linux-headers
            - libpcap-dev
            - protobuf-compiler

before_install:
    - sudo ovs-vsctl show
    - sudo iptables -F
    - for i in $(find /proc/sys/net/bridge/ -type f) ; do echo 0 | sudo tee $i ; done
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - export BUILD_TAG=$(date +%Y-%m-%d).${TRAVIS_JOB_NUMBER}
    - export PATH=${GOPATH}/bin:${PATH}

    - make WITH_EBPF=true install
    - make WITH_EBPF=true static

    - echo "--- DOCKER IMAGE ---"
    - make docker-image DOCKER_IMAGE=${DOCKER_IMAGE} DOCKER_TAG=${BUILD_TAG}
    - sudo -E docker login -e "${DOCKER_EMAIL}" -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - sudo -E docker tag ${DOCKER_IMAGE}:${BUILD_TAG} ${DOCKER_IMAGE}:latest
    - sudo -E docker push docker.io/${DOCKER_IMAGE}:${BUILD_TAG}
    - sudo -E docker push docker.io/${DOCKER_IMAGE}:latest

    - echo "--- BINARIES ---"
    - git reset --hard
    - git remote add binaries ${BINARIES_REPO}
    - git fetch binaries
    - git checkout -b travis-builds binaries/travis-builds
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - cp ${GOPATH}/bin/skydive skydive-latest
    - git add skydive-latest
    - git commit -m "${BUILD_TAG} travis build" --amend
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com" > .git/credentials
    - git push -f -q binaries travis-builds

# vim:set et ts=4 sw=4
